# https://cloud.google.com/run/docs/reference/yaml/v1

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${CLOUD_RUN_SERVICE_NAME}
  annotations:
    run.googleapis.com/ingress: 'internal-and-cloud-load-balancing'
    run.googleapis.com/ingress-status: 'internal-and-cloud-load-balancing'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        autoscaling.knative.dev/minScale: '0'
    spec:
      containerConcurrency: 50
      containers:
        - image: ${CONTAINER_IMAGE}
          resources:
            limits:
              cpu: '1'
              memory: '256Mi'
          env:
            ## System
            - name: GITHUB_SHA
              value: '${GITHUB_SHA}'
            - name: GOOGLE_CLOUD_PROJECT_ID
              value: '${GOOGLE_CLOUD_PROJECT_ID}'
            - name: GOOGLE_CLOUD_PROJECT_NUMBER
              value: '${GOOGLE_CLOUD_PROJECT_NUMBER}'
            - name: CLOUD_RUN_SERVICE_NAME
              value: '${CLOUD_RUN_SERVICE_NAME}'
            - name: ENVIRONMENT
              value: '${ENVIRONMENT}'

            ## Application
            - name: LOG_FORMAT
              value: '${LOG_FORMAT}'
            - name: BASE_URL
              value: '${BASE_URL}'
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
