## Types
- name: "🌱feature"
  description: "Feature addition"
  color: "0E8A16"
- name: "⚒️enhancement"
  description: "Feature improvement"
  color: "A2EEEF"
- name: "🐛bug"
  description: "Bug Fix"
  color: "D73A4A"
- name: "🐞hotfix"
  description: "High urgency bug fix"
  color: "D73A4A"
- name: "📝documentation"
  description: "Documentation improvement or addition"
  color: "0075CA"
- name: "💬quesion"
  description: "General inquiries or clarifications"
  color: "D876E3"
- name: "🔁duplicate"
  description: "This issue or pull request already exists"
  color: "CFD3D7"
- name: "🚫wontfix"
  description: "This will not be worked on"
  color: "CFD3D7"

## Version Resolver
- name: "🌟major"
  description: "Indicates a major release update"
  color: "FBCA04"

## Apps
- name: "🌐app: web"
  description: "Web application"
  color: "C5DEF5"
- name: "🌐app: api"
  description: "API application"
  color: "C5DEF5"

## Workspaces
- name: "📦package: jest"
  description: "Testing framework"
  color: "F9D0C4"
- name: "📦package: vitest"
  description: "Testing framework"
  color: "F9D0C4"
- name: "📦package: eslint"
  description: "Linting tool"
  color: "F9D0C4"
- name: "📦package: prettier"
  description: "Code formatting tool"
  color: "F9D0C4"
- name: "📦package: tsconfig"
  description: "TypeScript configuration"
  color: "F9D0C4"
- name: "📦package: ui"
  description: "User interface components"
  color: "F9D0C4"
- name: "📦package: types"
  description: "Shared TypeScript types for the project"
  color: "F9D0C4"
- name: "📦package: constants"
  description: "Shared constants package"
  color: "F9D0C4"
- name: "📦package: logger"
  description: "Logger specialized for Cloudrun"
  color: "F9D0C4"

## Github actions
- name: "🔄workflow: sync-labels"
  description: "Synchronize labels"
  color: "5319E7"
- name: "🔄workflow: release"
  description: "Deploy release"
  color: "5319E7"
- name: "🔄workflow: deployment"
  description: "Deploy application"
  color: "5319E7"
- name: "🔄workflow: get-details"
  description: "Retrieve detailed information"
  color: "5319E7"
- name: "🔄workflow: display-details"
  description: "Display detailed information"
  color: "5319E7"
- name: "🔄workflow: tests"
  description: "Test apps built in `apps/**`."
  color: "5319E7"
