services:
  api:
    container_name: torborepo-starter-api
    image: api:latest
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
    environment:
      - BASE_URL=http://nginx
      - LOF_FORMAT=text
    stop_signal: SIGINT
    ports:
      - 5002:5002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    external: true
