services:
  web:
    container_name: torborepo-starter-web
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - ./apps/web/.env
    environment:
      - PORT=3000
      - HOSTNAME="0.0.0.0"
      - NODE_ENV=production
      - BASE_URL=http://nginx
    stop_signal: SIGINT
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    external: true
